site_name: vQTLRandom
site_description: vQTL documentation
repo_url: https://github.com/jdc5884/StapletonLab
theme: readthedocs
docs_dir: 'doc_files/docs'
pages:
- Home: 
    - 'Introduction': 'intro/index.md'
    - 'vQTL': 'intro/vQTL.md'
- R/qtl Manual: 'qtl-manual.md'
- Workflow:
    - 'Getting Started': 'workflow/getstart.md'
    - 'Running vQTL' : 'workflow/RunvQTL.md'

